### ISSUE TITLE
Error in Dockerfile

### ISSUE THREAD

**Issue by andredev93** [BrewUp/BrewUpApiTemplate#6]
Hi,

In the Dockerfile in BrewUpApiTemplate/src the command at line 10 fails because it can't find the .csproj file in the current directory.
`COPY ["BrewUpApiTemplate.csproj", "BrewUpApiTemplate/"]`

Also at line 11 it looks like an error in the path because there is BrewUpApiTemplate twice:
`RUN dotnet restore "BrewUpApiTemplate/BrewUpApiTemplate/BrewUpApiTemplate.csproj"`

It can be solved by replacing with the following lines:
```
WORKDIR "/src/BrewUpApiTemplate"
COPY BrewUpApiTemplate/ .
RUN dotnet restore "BrewUpApiTemplate.csproj"
```

If I have permissions I could do the change in a branch, otherwise I could make a PR from a forked repo. 
Let me know what you think about the issue and how to solve it.
Thanks.

**Comment by Ace68** [comment]
Hi Andrea,
thank you for your email.
Please open a PR from a forked repo.

Thanks
Alberto Acerbis

Il giorno gio 9 feb 2023 alle ore 10:33 Andrea S ***@***.***>
ha scritto:

**Comment by Ace68** [comment]
Hi Andrea,
I accepted yout PR.
Thank you

Alberto

**Comment by peppemanzi** [comment]
I think that this issue can be closed. Do you agree?

**Comment by Ace68** [comment]
Issue closed, everyone can regenerate the template
